GeoscienceAustralia/Geodesy-Web-Services

src/main/resources/logback.xml
Use debugging logging level locally.
=> Turn off debug logging

src/main/java/au/gov/ga/geodesy/domain/model/CorsSiteLog.java, src/main/java/au/gov/ga/geodesy/port/adapter/geodesyml/CorsSiteLogFactory.java, src/main/java/au/gov/ga/geodesy/port/adapter/geodesyml/GeodesyMLSiteLogTranslator.java, src/main/java/au/gov/ga/geodesy/support/dozer/AgencyAgencyPropertyTypeConverter.java, src/main/java/au/gov/ga/geodesy/support/dozer/CharacterStringPropertyTypeConverter.java, src/main/java/au/gov/ga/geodesy/support/dozer/DozerUtils.java, src/main/java/au/gov/ga/geodesy/support/dozer/GeodesyMLSiteLogDozerTranslator.java, src/main/resources/dozer/ConverterMappings.xml, src/main/resources/dozer/FieldMappings.xml, src/test/java/au/gov/ga/geodesy/support/dozer/AgencyAgencyPropertyTypeConverterTest.java, src/test/java/au/gov/ga/geodesy/support/dozer/CharacterStringPropertyTypeConverterTest.java, src/test/java/au/gov/ga/geodesy/support/dozer/TranslateTest.java, src/test/resources/sitelog/ALIC.xml, src/test/resources/sitelog/testData/ALIC.xml
Completed first draft of translate.  All except dataStreams.
=> 11 sopac geodesyml translator 2

src/main/resources/dozer/ConverterMappings.xml
* Following Lazar's "Rename support.dozer to support.mapper.dozer"
=> Fix translate xml after package rename

src/main/java/au/gov/ga/geodesy/support/commandline/GeodesyMLCommandLine.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/AgencyAgencyPropertyTypeConverter.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLSiteLogDozerTranslator.java, src/main/java/au/gov/ga/geodesy/support/utils/GMLDateUtils.java, src/main/resources/dozer/FieldMappings.xml, src/main/resources/logback.xml, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/AgencyAgencyPropertyTypeConverterTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/TranslateTest.java, src/test/resources/sitelog/testData/MAT1.xml
* FInished translate with final elements
* Fixed contacts
* Improved logging (messages) in commandLine class
=> Command line all testfiles

runalltestinput.sh, src/main/java/au/gov/ga/geodesy/support/commandline/GeodesyMLCommandLine.java
* Necessary so I can specifiy EITHER an input file OR
an input directory
* Can specify output directory also (as always could)
=> Update runalltestinput.sh script to take argmuments

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLDozerEventListener.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLDozerEventListener_GnssReceiverType.java, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLDozerEventListener_GnssReceiverTypeTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/TranslateTest.java
* DateRemoved missing in one case in each sitelog file
as it is empty for last reeciver (since hasn't been removed yet)
and other code in the project drops empty elements as causes
problems elsewhere
=> Add missing elements from Receiver

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/DozerDelegate.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLDozerEventListenerFactory.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLDozerEventListener_GnssReceiverType.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLElementPopulator.java, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLDozerEventListener_GnssReceiverTypeTest.java
* The Abstract class GeodesyMLElementPopulator was written to do all
the work leaving the extending class only responsible for choosing the
elements it wants to check and set, and for the default object to set
=> Refactor element check and populator done for GnssReceiverType

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLDozerEventListenerFactory.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLDozerEventListener_GnssAntennaType.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLElementPopulator.java
* Also updated the GeodesyMLDozerEventListenerFactory to
fire off all events 
* Changed where this 'add missing elements' work done from postWritingDestinationValue() to mappingFinished()
=> Add missing Antenna elements

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePostitionTypeDateConverter.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePrimitivePropertyTypeEffectiveDatesConverter.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePrimitivePropertyTypeUtils.java, src/main/java/au/gov/ga/geodesy/support/utils/GMLDateUtils.java, src/main/java/au/gov/ga/geodesy/support/utils/GeodesyMLDecorators.java, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/converter/ApproximatePositionITRFConverterTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePostitionTypeDateConverterTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePostitionTypeStringConverterTest.java, src/test/java/au/gov/ga/geodesy/support/utils/ChangeTrackingDecoratorTest.java
* Dates and formatters had recently been updated
* dmsToDecimal had recently been written
* All tests pass
=> Fix tests after recent changes

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/GeodesyMLDozerEventListener_GnssAntennaType.java
* Simply output empty elements
=> Make Antenna elements optional

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePrimitivePropertyTypeUtils.java, src/main/java/au/gov/ga/geodesy/support/utils/GeodesyMLDecorators.java, src/test/java/au/gov/ga/geodesy/support/utils/IdDecoratorTest.java
* The ID Decorator I wrote before only applied them to the element passed in and not any others
* Updated to depth-first recursively add ids to any elements that has them
=> Add id's recursively

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/GeodesyMLDozerEventListenerFactory.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/GeodesyMLDozerEventListener_GnssAntennaType.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/HumiditySensorTypePopulator.java, src/main/java/au/gov/ga/geodesy/support/utils/GMLGmlTools.java, src/main/java/au/gov/ga/geodesy/support/utils/GMLMiscTools.java
* Also did a bit of refactoring
=> Add missing required Humidity Sensor elements

src/main/java/au/gov/ga/geodesy/support/utils/GeodesyMLDecorators.java, src/test/java/au/gov/ga/geodesy/support/utils/IdDecoratorTest.java
* In my reflection class I'd used "getDeclaredMethods()" instead of
"getMethods()" which meant that it only returned the methods of THIS
class and not it's parents
=> Fix ID decorator problem

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/AgencyAgencyPropertyTypeConverter.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/CodeListValueTypeConverter.java
* Fixed SecurityConstraint with CodeList
* Fixed Role
=> Fix Contacts

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLSiteLogDozerTranslator.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/MoreInformationAfterMapping.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/GeodesyMLDozerEventListenerFactory.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/MoreInformationTypePopulator.java, src/main/java/au/gov/ga/geodesy/support/utils/GMLMiscTools.java
=> Fix MoreInformation

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/GeodesyMLElementPopulator.java
* In the Populator classes
* For example field is of type String but output a default Double
=> Throw exceptions for using wrong default data type

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/SensorTypesPopulator.java
* Not all sensors have the same fields so make instanceof test
=> Fix SensorTypesPopulator for specific sensors

src/main/java/au/gov/ga/geodesy/support/mapper/decorator/GeodesyMLDecorators.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/GeodesyMLElementPopulator.java, src/main/java/au/gov/ga/geodesy/support/utils/GMLGeoTools.java, src/main/java/au/gov/ga/geodesy/support/utils/GMLReflectionUtils.java, src/test/java/au/gov/ga/geodesy/support/mapper/decorator/IdDecoratorTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/TranslateTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/populator/SiteLocationTypePopulatorTest.java
* I had the "set fields to this default" behaviour but this didn't
set the sub-fields from the default if they weren't set on the
parent's object (because the object on the parent wasn't null).
* This drills down into the sub-objects to set thos sub-sub-fields
=> Drill down into objects to set fields

src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLSiteLogDozerTranslator.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/FormInformationTypePopulator.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/GeodesyMLDozerEventListenerFactory.java
* Inc create it if not in Sopac at all
=> Fix missing required formInformation elements

src/test/java/au/gov/ga/geodesy/support/mapper/dozer/TranslateTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/populator/SiteLocationTypePopulatorTest.java
* Attempt - couldn't work it out in the time I allocated
Wrote some tests.  But 8 input SOPAC out of 653 fail and one
with this problem and dont' want to spend any more time on this
=> Fix country code

src/main/java/au/gov/ga/geodesy/support/commandline/GeodesyMLCommandLine.java, src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/GeodesyMLElementPopulator.java
=> Improve look of log to help report problems in translate

src/main/java/au/gov/ga/geodesy/support/utils/GMLMiscTools.java
* Missed one last import somehow
=> Upgrade to GeodesyML version 0.4

src/main/resources/dozer/ConverterMappings.xml, src/main/resources/dozer/FieldMappings.xml
* Had to do the dozer xml files also
=> Upgrade to GeodesyML version 0.4 - xml files

src/main/java/au/gov/ga/geodesy/port/adapter/geodesyml/GeodesyMLValidator.java, src/test/java/au/gov/ga/geodesy/port/adapter/geodesyml/GeodesyMLValidatorTest.java
class path resources injected by Spring in WebAppConfig
Unit test updated to pass dummy args to constructor  just to make it compile. Still need to fix this so the test passes.
=> parameterise the GeodesyMLValidator class

src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/PressureSensorMapper.java, src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapper.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/HumiditySensorMapperTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/PressureSensorMapperTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapperTest.java, src/test/resources/sitelog/geodesyml/MOBS-sensors.xml, src/test/resources/sitelog/geodesyml/MOBS.xml
Despite the branch name this is about adding support for the pressureSensor element.
Two commits. One for the mapping and test for pressure sensor, one for adding pressureSensors to the SiteLogMapper, reorganising the SiteLogMapperTest and testing the pressureSensors elements.
We might want to change this back to testing one large siteLog file that has everything in it but it seemed to make sense to separate the concerns. 
My commit comment "Add pressure sensors to site log test" is also not very good as that commit was about the mapper, the test just part of it.
=> Create pressure sensor mapping

src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/BigDecimalToStringConverter.java, src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapper.java, src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/TemperatureSensorMapper.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapperTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/TemperatureSensorMapperTest.java, src/test/resources/sitelog/geodesyml/MOBS-sensors.xml
includes mapper, test, test file and SiteLogMapper (and test) updates.
whereas in my last PR I used a separate commit for the SiteLogMapper stuff I think it is unnecessary. But I am happy to do it that way if anyone thinks it is important.
=> Add temperature sensor mapper

.idea/misc.xml, .idea/vcs.xml, geodesy-domain-model.iml, pom.xml
* To generate GIT-SHA into MANIFEST.MF
=>  #4 - Add maven build-number plugin

pom.xml
* Add timeFormated time stamp to Manifest
* Add git-branch to Manifest
* Removed project-version from Manifest as same
information available in Implementation-Version
=> #4 - Build Number

src/main/java/au/gov/ga/geodesy/support/utils/GMLDateUtils.java, src/test/java/au/gov/ga/geodesy/support/mapper/dozer/TranslateTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SensorEquipmentMapperTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/TemperatureSensorMapperTest.java, src/test/java/au/gov/ga/geodesy/support/utils/GMLDateUtilsTest.java
* Fixed JUnit import to re-become a TestNG one (must have been a mistake by Heya)
=> Fixed unit test imports

src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/FormInformationMapper.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/FormInformationMapperTest.java
Please review FormInformation mapper.
=> Created a new mapper for FormInformation type

src/test/java/au/gov/ga/geodesy/port/adapter/rest/UploadAliceGeodesyMLSiteLogRestTest.java
was expected 200(OK) but should be 201(CREATED)
=> Change expected http status

src/main/java/au/gov/ga/geodesy/domain/model/sitelog/EffectiveDates.java
Reverts GeoscienceAustralia/geodesy-domain-model#196
=> Revert "break build to test email notifications"

runalltestinput.sh, src/main/java/au/gov/ga/geodesy/support/commandline/GeodesyMLCommandLine.java
* Honour new resource directory structure
=> Fix command-line translation script

src/test/java/au/gov/ga/geodesy/support/mapper/dozer/TranslateTest.java, src/test/resources/sitelog/testData/ALIC.xml
re: Issues with Github commit seeming different to local - I made another change and
committed again.  Although it isn't looking like I fully expect it should, it should be ok.
See the two deleted lines at the bottom.  If you look 5 or so lines above you can see
those there.
=> Fix alic date tests4

src/main/java/au/gov/ga/geodesy/domain/model/equipment/EquipmentFactory.java, src/main/java/au/gov/ga/geodesy/domain/model/sitelog/LogItemVisitor.java, src/main/java/au/gov/ga/geodesy/domain/model/sitelog/MultipathSourceLogItem.java, src/main/java/au/gov/ga/geodesy/domain/model/sitelog/PossibleProblemSourceLogItem.java, src/main/java/au/gov/ga/geodesy/domain/model/sitelog/RadioInterference.java, src/main/java/au/gov/ga/geodesy/domain/model/sitelog/SignalObstructionLogItem.java, src/main/java/au/gov/ga/geodesy/domain/model/sitelog/SiteLog.java, src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SignalObstructionMapper.java, src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapper.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SignalObstructionMapperTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapperTest.java, src/test/resources/sitelog/geodesyMLTestData/METZ-signalObstructionSet.xml
Mapper and tests
Also added new mapper to SiteLogmapper and tests.
requires change to ogc-schemas in PR10
=> Add Signal Interference mapper

src/main/java/au/gov/ga/geodesy/domain/model/sitelog/SiteLog.java, src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/MultipathSourcesMapper.java, src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapper.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/MultipathSourcesMapperTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SignalObstructionMapperTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapperTest.java, src/test/resources/sitelog/geodesyMLTestData/METZ-multipathSources.xml
Mapper and tests
Also added new mapper to SiteLogmapper and tests.
=> Add MultipathSource mapper

src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapperTest.java
@lbodor I changed the notification settings and want to test it by breaking the build again. would you like to share in the blame by clicking merge?
=> break the build to test notification settings

src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapperTest.java
Reverts GeoscienceAustralia/geodesy-domain-model#216
=> Revert "break the build to test notification settings"

pom.xml
* https://github.com/GeoscienceAustralia/eGeodesy/wiki/SonarQube-analysis
* https://sonar.gadevs.ga/
=> Add sonar analysis

eclipse-format-java-modest.xml
=> Set default continuation indentation level to 1

src/main/java/au/gov/ga/geodesy/domain/model/sitelog/EffectiveDates.java, src/test/java/au/gov/ga/geodesy/domain/model/sitelog/EffectiveDatesComparableTest.java, src/test/resources/sitelog/geodesyMLTestData/WGTN-localEpisodicEvents.xml
* Specifically with EffectiveDates
* And test data used for LocalEpisodicEvents
=> Fix bug in LocalEpisodicEvents

src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/InstantToTimePositionConverter.java, src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapper.java, src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SurveyedLocalTieMapper.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapperTest.java, src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SurveyedLocalTieMapperTest.java
Please review SurveyedLocalTie Mapper. Thanks.
=> Surveyed local ties

pom.xml
* Was previously deleted
* Re-added but Using a property based approach so there remains only one 'surefire-plugin'.
=> Re-add integration tests

pom.xml
* BE SURE TO merge eGeodesy before this
=> GEOD-51 Moved Sonar POM parts to eGeodesy parent

pom.xml
* MERGE THIS AFTER egeodesy-parent
=> GEOD-51 Move to use eGeodesy-parent as parent pom

src/main/java/au/gov/ga/geodesy/port/adapter/rest/SiteLogEndpoint.java
Content type needs to be set before the response body.
=> Ensure correct content-type

src/main/resources/db/add-site-network.xml, src/main/resources/db/geodesy-database-changelog.xml
created two new tables cors_site_network and cors_site_network_relation
=> create new table cors_site_network and cors_site_network_relation

src/main/resources/db/add-site-network.xml, src/main/resources/db/geodesy-database-changelog.xml
Reverts GeoscienceAustralia/geodesy-domain-model#311
=> Revert "Revert "create new table cors_site_network and cors_site_network_relation""

src/main/resources/db/drop-temp-tables.xml, src/main/resources/db/geodesy-database-changelog.xml
drop temp tables - temp_9_character_data and temp_site_network
=> drop temp tables used for add 9 characterid and network

src/main/resources/db/add-comments-to-new-responsible-party-tables.xml, src/main/resources/db/creante-new-responsible-party-tables.xml, src/main/resources/db/geodesy-database-changelog.xml, src/main/resources/db/migrate-site-responsible-party-data-to-new-table.sql
create new sitelog responsible party tables and populate the tables
=> Update responsible party

src/main/resources/db/geodesy-database-changelog.xml, src/main/resources/db/rename-responsible-role-column.xml
change column name "responsible_role" to "responsible_role_id" in sitelog_responsible_party table
change foreign key name according to new column name
=> change column name to responsible_role_id

src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/StringToCodeListValueConverter.java, src/test/java/au/gov/ga/geodesy/port/adapter/rest/UploadAliceGeodesyMLSiteLogRestTest.java
See https://www.w3.org/TR/2000/WD-xml-2e-20000814#AVNormalize.
=> Do not use normalised codeListValue attributes

src/test/java/au/gov/ga/geodesy/port/adapter/rest/UploadAliceGeodesyMLSiteLogRestTest.java
Order of /gnssReceivers is unknown
=> Remove non-deterministic test check

src/test/java/au/gov/ga/geodesy/domain/model/sitelog/SiteLogRepositoryTest.java
We upload all site logs at system-test time.
=> Stop uploading all site logs at unit-test time

gws-core/src/main/resources/db/add-table-column-comments-part1.xml, gws-core/src/main/resources/db/add-table-column-comments-part2.xml, gws-core/src/main/resources/db/add-table-column-comments-part3.xml, gws-core/src/main/resources/db/geodesy-database-changelog.xml
add table and column comments to geodesy tables - this is the part one of the changes
=> add-table-column-comments-part1

gws-core/src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/GnssAntennaMapperTest.java, gws-core/src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/GnssReceiverMapperTest.java, gws-core/src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/HumiditySensorMapperWithNullValuesTest.java, gws-core/src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SensorEquipmentMapperTest.java, gws-core/src/test/resources/sitelog/geodesyml/custom/MOBS-null-numerics.xml
fix some existing tests that were using integer values
=> add test for Double mapping

gws-open-am/Dockerfile
See https://bugster.forgerock.org/jira/browse/OPENAM-1325.
=> Deploy OpenAM under non-root context

gws-core/src/main/resources/db/add-delete-column-in-sitelog.xml, gws-core/src/main/resources/db/geodesy-database-changelog.xml
add two columns "delete_time" and "delete_reason" into sitelog_tables;
also add comments on two new columns
=> add delete_date and delete_reason columns into sitelog tables

gws-open-am/config/embedded-directory-data.ldif, gws-open-am/config/service-cfg.xml
Add http://localhost:5555/login and http://localhost:5555.
=> Configure OpenAM Oauth2 redirects

gws-open-am/config/embedded-directory-data.ldif, gws-open-am/config/service-cfg.xml
Add http://localhost:5555/auth.html for login and http://localhost:5555
for logout.
=> Adjust oauth2 client redirects

gws-core/pom.xml, gws-core/src/main/java/au/gov/ga/geodesy/domain/model/UserRegistration.java, gws-core/src/main/java/au/gov/ga/geodesy/domain/model/UserRegistrationRepository.java, gws-core/src/main/java/au/gov/ga/geodesy/domain/model/UserRegistrationRepositoryCustom.java, gws-core/src/main/java/au/gov/ga/geodesy/domain/model/UserRegistrationRepositoryImpl.java, gws-core/src/main/java/au/gov/ga/geodesy/domain/model/event/Event.java, gws-core/src/main/java/au/gov/ga/geodesy/domain/model/event/UserRegistrationReceived.java, gws-core/src/main/java/au/gov/ga/geodesy/domain/service/UserRegistrationNotificationService.java, gws-core/src/main/java/au/gov/ga/geodesy/port/Notification.java, gws-core/src/main/java/au/gov/ga/geodesy/port/NotificationPort.java, gws-core/src/main/java/au/gov/ga/geodesy/port/adapter/smtp/SMTPNotificationAdapter.java, gws-core/src/main/java/au/gov/ga/geodesy/port/adapter/sns/SnsNotificationAdapter.java, gws-core/src/main/java/au/gov/ga/geodesy/port/adapter/sns/package-info.java, gws-core/src/main/java/au/gov/ga/geodesy/support/spring/GeodesyServiceConfig.java, gws-core/src/main/resources/db/add-user-registration.xml, gws-core/src/main/resources/db/geodesy-database-changelog.xml, gws-core/src/test/java/au/gov/ga/geodesy/port/adapter/mock/InMemoryNotificationAdapter.java, gws-core/src/test/java/au/gov/ga/geodesy/port/adapter/rest/UserRegistrationRestITest.java, gws-core/src/test/java/au/gov/ga/geodesy/support/spring/GeodesyServiceTestConfig.java
* Rest endpoint
* Data model
* SNS notification
=> Add user registration

gws-geoserver/data/app-schema-cache/au/gov/ga/schemas/geodesyml/0.4/equipment.xsd, gws-geoserver/data/app-schema-cache/au/gov/ga/schemas/geodesyml/0.4/fieldMeasurement.xsd, gws-geoserver/data/app-schema-cache/au/gov/ga/schemas/geodesyml/0.4/geodeticEquipment.xsd
XSD file are copied from GeodesyML/schemas.
=> Update geoserver xsd cache

gws-system-test/pom.xml, gws-system-test/src/test/java/au/gov/ga/geodesy/gws/systemtest/AuthorizationSystemTest.java, gws-system-test/src/test/java/au/gov/ga/geodesy/gws/systemtest/BaseSystemTest.java, gws-system-test/src/test/java/au/gov/ga/geodesy/gws/systemtest/SystemTestResources.java, gws-system-test/src/test/java/au/gov/ga/geodesy/gws/systemtest/SystemTestResourcesTest.java, gws-system-test/src/test/java/au/gov/ga/geodesy/gws/systemtest/UploadSiteLogsSystemTest.java
For example , `java -cp "target/dependency/*" org.testng.TestNG /path/to/testng.xml`
=> Prepare test-jar for stand-alone testng invocation

.travis.yml
Reverts GeoscienceAustralia/Geodesy-Web-Services#466
=> Revert "Build branch `next`"

gws-core/src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/InstantToTimePositionConverter.java
Map yyyy to yyyy-01-01T00:00.000Z and yyyy-MM to
yyyy-MM-01T00:00:00.000Z.
=> Accept partial dates

gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/AssociatedDocument.java, gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/AssociatedDocumentRepository.java, gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/AssociatedDocumentRepositoryCustom.java, gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/AssociatedDocumentRepositoryImpl.java, gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/SiteLog.java, gws-core/src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/AssociatedDocumentMapper.java, gws-core/src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/GenericMapper.java, gws-core/src/main/java/au/gov/ga/geodesy/support/spring/GeodesyRepositoryRestMvcConfig.java, gws-core/src/main/resources/db/add-associated-document-table.xml, gws-core/src/main/resources/db/geodesy-database-changelog.xml, gws-core/src/test/java/au/gov/ga/geodesy/domain/model/Repositories.java, gws-core/src/test/java/au/gov/ga/geodesy/domain/model/sitelog/AssociatedDocumentRepositoryITest.java, gws-core/src/test/java/au/gov/ga/geodesy/port/adapter/rest/SiteLogEndpointITest.java, gws-core/src/test/java/au/gov/ga/geodesy/port/adapter/rest/UploadAliceGeodesyMLSiteLogRestITest.java, gws-core/src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/AssociatedDocumentMapperTest.java, gws-core/src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapperITest.java, gws-core/src/test/resources/sitelog/geodesyml/custom/ALIC-with-2-associated-documents.xml, gws-core/src/test/resources/sitelog/geodesyml/custom/MOBS.xml
As suggested, I have included code that models the table entity, retrieves/saves associated documents from/into the table, and field mapping to GeodesyML plus unit and integration tests. It is now ready for review and approval.
=> Create AssociatedDocument table, and add domain model, repository and field mapper

gws-core/pom.xml, gws-core/src/main/java/au/gov/ga/geodesy/port/adapter/rest/SkeletonEndpoint.java, gws-core/src/test/java/au/gov/ga/geodesy/port/adapter/rest/SkeletonEndpointITest.java, gws-parent/pom.xml
1. Need to change RinexFileHeader to add one "observer agency" line
2. For all review and comments for assembler really working?
=> Api for skeleton file request WIP

gws-core/pom.xml
https://www.osgeo.org/foundation-news/new-osgeo-repo/
=> Switch to repo.osgeo.org

gws-core/src/main/java/au/gov/ga/geodesy/port/adapter/rest/SkeletonEndpoint.java
Details in https://gajira.atlassian.net/secure/RapidBoard.jspa?rapidView=54&projectKey=CK&modal=detail&selectedIssue=GNSSSM-94
=> Use Site Metadata Custodian for Skeleton file endpoint instead of Site Contacts

gws-core/src/main/java/au/gov/ga/geodesy/port/adapter/rest/SkeletonEndpoint.java, gws-core/src/test/java/au/gov/ga/geodesy/port/adapter/rest/SkeletonEndpointITest.java
=> Fix signal type receiver association

gws-core/src/main/resources/db/add-associated-document-table.xml
This change set was already applied to the test database, so it can't be
modified.
=> Restore setTableRemarks
