GeoscienceAustralia/Geodesy-Web-Services

- pom.xml
- src/test/java/au/gov/ga/geodesy/support/testng/TestDependencyController.java
This is useful when running a single test method, e.g.,
mvn test -Dtest=SiteRepositoryTest#saveAllSiteLogs
> Optionally ignore test dependencies

- pom.xml
* Caused when surefire runs and on the Mac it has
an App 'ForkedBooter' that is associated with it
* See https://somethingididnotknow.wordpress.com/2014/07/23/forkedbooter-steals-window-focus-on-mac-os-while-maven-is-running/
> Prevent annoying context switch on MacOSX

- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/GnssAntennaTypePopulator.java
- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/GnssReceiverTypePopulator.java
- src/test/java/au/gov/ga/geodesy/support/mapper/dozer/populator/GnssReceiverTypePopulatorTest.java
GnssReceiverType and GnssAntennaType have a SerialNumber (defined on it) and a manufacturerModel (defined on BaseGeodeticEquipmentType, which is the Grandparent of those).  We are uncertain exactly how to handle this multiplicity of what seems to be an element with the same purpose. For the mean time we will have both elements. This code will make sure of this requirement. It will make an empty one the same as the other or "" if neither is defined.
> Sort out serial numbers

- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/GeodesyMLSiteLogDozerTranslator.java
- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/MoreInformationAfterMapping.java
- src/test/java/au/gov/ga/geodesy/support/mapper/dozer/converter/MoreInformationAfterMappingTest.java
* Due to validation and schema need one in GeodesyML
* Create a MoreInformationType and populate with defaults
> Manage when Sopac's MoreInformation doesnt exist

- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/SiteLocationTypePopulator.java
* Needed to map what being input as a Country to the actual
country used in the ISO Code mapping
* Returned "???" for unknowns
> Fix country codes

- pom.xml
- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/CodeListValueTypeConverter.java
- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/CodeListValueTypeConverterInstanceBase.java
- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/CodeListValueTypeConverterInstanceCountryCodeType.java
- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/CodeListValueTypeConverterInstanceDefault.java
- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/CodeListValueTypeConverterInstanceFactory.java
- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/SiteLocationTypePopulator.java
- src/main/java/au/gov/ga/geodesy/support/utils/GMLMiscTools.java
- src/test/java/au/gov/ga/geodesy/support/mapper/dozer/TranslateTest.java
- src/test/java/au/gov/ga/geodesy/support/mapper/dozer/converter/CodeListValueTypeConverterInstanceCountryCodeTypeTest.java
- src/test/java/au/gov/ga/geodesy/support/mapper/dozer/converter/CodeListValueTypeConverterTest.java
* Due to Dozer working with super types, I couldn't have a CountryCode to/from String mapper.  Instead there is a Factory in the CodeLists to / from String mapper that selects that specific super types (either CountryCode or default (everything else))
> #113 Update since now using CountryCode CodeLists

- pom.xml
- src/main/java/au/gov/ga/geodesy/domain/model/event/Event.java
- src/main/java/au/gov/ga/geodesy/domain/model/event/InvalidSiteLogReceived.java
- src/main/java/au/gov/ga/geodesy/domain/model/event/SiteLogReceived.java
- src/main/java/au/gov/ga/geodesy/domain/model/event/SiteUpdated.java
- src/main/java/au/gov/ga/geodesy/domain/model/event/WeeklySolutionAvailable.java
- src/main/java/au/gov/ga/geodesy/domain/service/NotificationService.java
- src/main/java/au/gov/ga/geodesy/port/NotificationPort.java
- src/main/java/au/gov/ga/geodesy/port/adapter/smtp/SMTPAdapter.java
- src/main/java/au/gov/ga/geodesy/port/adapter/smtp/SMTPNoficationAdapter.java
- src/main/java/au/gov/ga/geodesy/support/email/GeodesyMailMessage.java
- src/main/java/au/gov/ga/geodesy/support/email/SpringMailAdapter.java
- src/main/java/au/gov/ga/geodesy/support/properties/GeodesyMailConfig.java
- src/main/java/au/gov/ga/geodesy/support/properties/GeodesyNotificationsConfig.java
- src/main/java/au/gov/ga/geodesy/support/spring/GeodesyServiceConfig.java
- src/main/java/au/gov/ga/geodesy/support/utils/GeodesyConfigUtil.java
- src/main/resources/app.yaml
- src/test/java/au/gov/ga/geodesy/domain/service/NotificationServiceTest.java
- src/test/java/au/gov/ga/geodesy/support/properties/GeodesyNotificationsConfigTest.java
- src/test/java/au/gov/ga/geodesy/support/spring/TestAppConfig.java
- src/test/java/au/gov/ga/geodesy/support/utils/GeodesyConfigUtilTest.java
- src/test/resources/email.properties
- src/test/resources/notifications.properties
Email Notifications setup.  Two properties files used:
* email.properties - config for sending email
* notifications.properties - To and From email addresses
Attempted yaml properties but proved not as easy as expected. Something that could be re-attempted later.  Problem was that the / a PropertySourcesPlaceholderConfigurer had to be setup and refer to the yaml file explicitly.  https://github.com/GeoscienceAustralia/geodesy-domain-model/commit/2eff0decf513903fcd27c36538a92f527245adae was a commit for yaml that I later removed.
resolve #68
> 68 email notifications

- src/main/java/au/gov/ga/geodesy/support/spring/GeodesyRepositoryRestMvcConfig.java
The JSON mapper was throwing an error similar to a Lazy Initialization
exception when the object contained an unitialised collection, fixed this by adding a serialisation feature configuration setting.
Symptom: after adding a sitelog, try to access the endpoint http://localhost:8080/geodesy-web-services/siteLogs{?page,size,sort}
> Configure mapper to work with empty beans

- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePositionTypeInstantConverter.java
- src/test/java/au/gov/ga/geodesy/support/mapper/decorator/ChangeTrackingDecoratorTest.java
- src/test/java/au/gov/ga/geodesy/support/mapper/dozer/DozerDelegateTest.java
- src/test/java/au/gov/ga/geodesy/support/mapper/dozer/TranslateTest.java
- src/test/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePositionTypeInstantConverterTest.java
- src/test/resources/sitelog/testData/AMC2.xml
- src/test/resources/sitelog/testData/ARTU.xml
- src/test/resources/sitelog/testData/CRAO.xml
- src/test/resources/sitelog/testData/CRO1.xml
- src/test/resources/sitelog/testData/IRKJ.xml
- src/test/resources/sitelog/testData/ZAMB.xml
* Why the new sopac sitelog files - The input Sopac Sitelog files were failing due to date formats
We want to leave the originals as they were.  But i need the tests
on these to run to task for other aspects.  So I made copies and
fixed the date formats
> Fix Sopac to GeodesyMl translate after Date to Instant change

- src/main/java/au/gov/ga/geodesy/domain/model/equipment/EquipmentRepository.java
- src/main/java/au/gov/ga/geodesy/support/spring/GeodesyRepositoryRestMvcConfig.java
- src/main/java/au/gov/ga/geodesy/support/spring/RootResourceProcessor.java
This pull request explicitly sets the exported resource name to "equipment". By default, spring-data-rest sees the equipment entity class, and generates the "equipments" resource path.
> Rename equipment resource path element

- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePrimitivePropertyTypeStringConverter.java
- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePrimitivePropertyTypeUtils.java
- src/test/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePrimitivePropertyTypeUtilsTest.java
* Fixed the case where the EffectiveDate from the data is null.
Previously 1/1/1970 TimeInstantType being returned.
Now returns TimePeriodType with empty lists for begin and end.
* Also fixed minor date tests
> Fix problem with incomplete EffectiveDates in Dozer

- pom.xml
- src/main/java/au/gov/ga/geodesy/port/adapter/geodesyml/SopacFileTranslator.java
- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/converter/TimePrimitivePropertyTypeEffectiveDatesConverter.java
- src/main/java/au/gov/ga/geodesy/support/mapper/dozer/populator/RadioInterferencesTypePopulator.java
- src/test/java/au/gov/ga/geodesy/port/adapter/rest/UploadZIMJGeodesyMLSiteLogRestTest.java
- src/test/java/au/gov/ga/geodesy/support/TestResources.java
- src/test/java/au/gov/ga/geodesy/support/mapper/decorator/IdDecoratorTest.java
- src/test/java/au/gov/ga/geodesy/support/mapper/dozer/TranslateTest.java
- src/test/resources/sitelog/testData/ZIMJ-radioInterference-noEffectiveDates.xml
- src/test/resources/sitelog/testData/ZIMJ-radioInterference-withEffectiveDates.xml
- src/test/resources/sitelog/testData/ZIMJ-radioInterference-withEffectiveDatesNoToForm1.xml
- src/test/resources/sitelog/testData/ZIMJ-radioInterference-withEffectiveDatesNoToForm2.xml
Make sure that Sopac EffectiveDate is translated properly to GeodesyML:
* If null then geodesyml's sitelog.radiointerference.validtime is null
* if has both a from and to date then geodesyml's sitelog.radiointerference.validtime has same values in beginPosition and endPosition
* If has one or the other of from and to, then geodesyml's sitelog.radiointerference.validtime has a corresponding null for the beginPosition or endPosition
This change:
* Also add back in the Dozer tests into the maven testing
> Fix EffectiveDate in RadioInterference dozer mapper

- src/main/java/au/gov/ga/geodesy/port/adapter/rest/GnssReceiverEndpoint.java
This fixes the currently failing GnssReceiverEndpointTest. Without direct field access, request parameter binding cannot access immutable fields of GnssReceiver.
> Turn on direct field access web data binding

- src/main/java/au/gov/ga/geodesy/domain/model/equipment/Equipment.java
It was mistakenly set to non-nullable by #3d124bf.
> Make equipment type nullable again

- src/main/java/au/gov/ga/geodesy/port/adapter/rest/GnssReceiverEndpoint.java
- src/main/java/au/gov/ga/geodesy/port/adapter/rest/SetupEndpoint.java
- src/test/java/au/gov/ga/geodesy/port/adapter/rest/GnssReceiverEndpointTest.java
- src/test/java/au/gov/ga/geodesy/port/adapter/rest/SetupEndpointTest.java
By default, spring data rest generates self links for all search results. In case of custom queries, we need to use a specific assembler to ensure that the self links are generated.
> Self links

- src/test/java/au/gov/ga/geodesy/port/adapter/smtp/SMTPNotificationAdapterTest.java
- src/test/java/au/gov/ga/geodesy/support/properties/GeodesyNotificationsConfigTest.java
* Ones that setup a Spring Context as they
didn't seem to create code coverage in Sonar.
* The non-context junit tests seem to be ok.
> Rewrote key Junit tests to TestNg

- pom.xml
* Only one jacoco listener for JUnit or TestNg can be used.
GEOD-52 is to rewrite the JUnit tests as TestNg / Hamcrest
So as of this commit not all tests will pass.  But mmm, a little hard
to tell as there are tests failing for what actually looks to be other reasons.
> Add Sonar code coverage

- pom.xml
* Do this after eGeodesy-parent
* Separate Unit (default build),
* integration (standalone + one for sonar coverage)
* functional / system (standalone + one for sonar coverage)
* See https://github.com/GeoscienceAustralia/eGeodesy/wiki/Testing
> GEOD-43 - testing segregation

- pom.xml
- src/main/resources/liquibase-postgres-reference.properties
Running `mvn -Pliquibase liquibase:dropAll` will drop all objects in
your reference database, which is the one that integration tests
(i.e., hibernate) run against.
> Add mvn profile for running liquibase

- src/main/java/au/gov/ga/geodesy/support/spring/GeodesyRestMvcConfig.java
CORS is setup for all endpoints in geodesy-web-services/src/main/webapp/WEB-INF/web.xml.
> Remove redundant cors setup

- src/main/resources/db/geodesy-database-changelog.xml
- src/main/resources/db/rename-responsible-party-column-name.sql
when rename a table column, Liquibase converted into several separate commands - create column, drop column, add fk, drop fk.  It has caused null value error when run it, because referenced column was not there any more. It could be a Liquibase bug. To prevent it happen again, I have to submit the changes as sql file rather than using the XML file generated by Liquibase.
> rename sitelog_responsible_party column name

- pom.xml
- travis/build.sh
This ensures that things just work. Once people get the hang of things,
they can control this behaviour using maven property `skip.createDb`.
> Run a clean database when running tests

- gws-core/src/main/resources/db/drop-old-responsible-party-table.xml
- gws-core/src/main/resources/db/geodesy-database-changelog.xml
responsible_party table was replaced by sitelog_responsible_party, so it can be dropped.
two columns, site_metadata_custodian_id and site_contact_id, in sitelog_site that are reference to old responsible_party can also be dropped
> drop-old-responsible-party

- docker-compose.yaml
Geoserver requires database objects that geodesy-web-services creates.
> First run gws-webapp, then gws-geoserver

- gws-system-test/pom.xml
System tests can now be run with `java -jar target/gws-system-test.jar
-testjar target/gws-system-test.jar`.
> Package system tests into an executable uber jar

- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/SiteLog.java
- gws-core/src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/ResponsiblePartiesMapper.java
- gws-core/src/main/resources/db/add-index-column-to-responsible-parties.xml
- gws-core/src/main/resources/db/geodesy-database-changelog.xml
- gws-core/src/test/java/au/gov/ga/geodesy/port/adapter/rest/UploadAliceGeodesyMLSiteLogRestITest.java
The order of responsible party types is defined in GeodesyML in `siteLog.xsd`.
The order of responsible party values is defined by the order in which
they appear in a given GeodesyML site log document.
> Respect the order of responsible parties

- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/equipment/EquipmentFactory.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/CollocationInformation.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/CollocationInformationLogItem.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/EquipmentLogItem.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/FrequencyStandardLogItem.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/GnssAntennaLogItem.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/GnssReceiverLogItem.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/LocalEpisodicEffectLogItem.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/LogItem.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/LogItemVisitor.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/OtherInstrumentationLogItem.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/PossibleProblemSourceLogItem.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/SensorEquipmentLogItem.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/SiteLog.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/SurveyedLocalTie.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/SurveyedLocalTieLogItem.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/service/CorsSiteService.java
- gws-core/src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/CollocationInformationMapper.java
- gws-core/src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/LogItemPropertyTypeMapper.java
- gws-core/src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapper.java
- gws-core/src/main/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SurveyedLocalTieMapper.java
- gws-core/src/main/resources/db/add-date-inserted-change-tracking-columns.xml
- gws-core/src/main/resources/db/geodesy-database-changelog.xml
- gws-core/src/main/resources/db/rename-change-tracking-columns.xml
- gws-core/src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/CollocationInformationMapperTest.java
- gws-core/src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/LogItemPropertyTypeMapperTest.java
- gws-core/src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SiteLogMapperITest.java
- gws-core/src/test/java/au/gov/ga/geodesy/support/mapper/orika/geodesyml/SurveyedLocalTieMapperTest.java
Persist site log items along with their change tracking attributes, but disregard deleted log items when computing setups.
Note that this pull request is stacked on top of #505.
> Handle change tracking of log items

- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/NetworkTenancy.java
Include all properties and exclude the database key.
> Fix equals method for NetworkTenancy

- aws/infra-base.yaml
> Update OpenAM AMI

- travis/build.sh
In a multi-module project, maven can't update dependencies without
installing all modules.
> CI, install and resolve dependencies in one step

- travis/build.sh
> Reduce CI log output

- gws-tomcat/entrypoint.sh
- gws-tomcat/env.sh
This is a problem when running bash in docker, where any error at the
promp terminates the container.
> Don't exit on error from docker containers

- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/equipment/HumiditySensorRepository.java
- gws-core/src/main/java/au/gov/ga/geodesy/domain/service/SetupService.java
This change could optionally be rolled back for the next release to production,
because humidity sensors are no longer created for CorsSetups.
> Delete humidity sensors when deleting equipment

- gws-core/src/main/java/au/gov/ga/geodesy/domain/model/sitelog/SiteLog.java
This is wasteful when not all components of a site log need to be loaded
from the database, but all components need to be loaded when we generate
site logs in json format.
> Use eager JPA fetch type

- aws/deploy.sh
Alternative solution is to remove "-u" from "set -eEuo pipefail". However, unset variables are a common cause of bugs in shell scripts, so having unset variables cause an immediate exit is often highly desirable behavior.
> Fix unset variables error in aws/deploy.sh

- .travis.yml
- gws-core/pom.xml
- gws-core/src/main/java/au/gov/ga/geodesy/port/adapter/geodesyml/GeodesyMLValidator.java
- gws-core/src/test/java/au/gov/ga/geodesy/port/adapter/geodesyml/GeodesyMLValidatorTest.java
- gws-core/src/test/java/au/gov/ga/geodesy/support/spring/GeodesyServiceTestConfig.java
- gws-parent/pom.xml
- gws-system-test/pom.xml
- gws-webapp/pom.xml
- gws-webapp/src/main/java/au/gov/ga/geodesy/support/spring/WebAppConfig.java
- pom.xml
- travis/build.sh
New release of GWS, which grabs the now released dependencies at version 0.2.0 (using GeodesyML 0.4) and 0.3.0 of igssitelog-java-bindings, which does not depend on GeodesyML.
> Release 0.2.2

- gws-system-test/src/main/resources/testng.xml
Currently system tests are failling with
LifecycleEvent - ValidateService
Script - validate-service.sh
[stderr][TestNG] [ERROR]
[stderr]Cannot instantiate class au.gov.ga.geodesy.gws.systemtest.UploadSiteLogsSystemTest
This change should give us more information about the failure
> Increase testng verbosity

- gws-parent/pom.xml
We are at spring 4.3.6.RELEASE, but gnss-support-rinex.jar is bringing in a
later version, which may be causing the following intermittent system
test failure:
```
...
[stdout] at org.springframework.test.context.BootstrapUtils.createCacheAwareContextLoaderDelegate(BootstrapUtils.java:98)
[stdout] ... 28 more
[stdout]Caused by: java.lang.NoClassDefFoundError: org/springframework/core/KotlinDetector
[stdout] at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:187)
[stdout] at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:138)
[stdout] ... 30 more
[stdout]Caused by: java.lang.ClassNotFoundException: org.springframework.core.KotlinDetector
[stdout] at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[stdout] at …
```
> Exclude transitive spring dependency

- gws-core/src/main/java/au/gov/ga/geodesy/port/adapter/rest/SkeletonEndpoint.java
- gws-core/src/test/java/au/gov/ga/geodesy/port/adapter/rest/SkeletonEndpointITest.java
- gws-core/src/test/resources/sitelog/geodesyml/custom/ALIC.xml
Also updated tests to compare the entire response body to the expected skeleton file content.
> Truncate Agency Name in Skeleton Endpoint

- aws/deploy-local.sh
When running `./aws/deploy-local.sh` in LocalStack, an IAM role and policy `arn:aws:iam::688660191997:role/gnss-metadata-document-storage-local-access` will be created in geodesy-operations account, which will cause error in next run. It seems that LocalStack does not support testing of security configuration, IAM policies, etc. So, add terraform target flag to s3 bucket to skip the creation of IAM role/policy.
> Add aws_s3_bucket resource address to terraform target flag

- aws/terraform/document_storage.tf
Currently when uploading images to the document storage bucket,  I still got error messages: 
`Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 27C65B9719E2A5C4)`.
With this bucket policy deployed as testing, I successfully uploaded and deleted images to/from the bucket for ALIC sitelog.
> Add bucket policy to allow cross account access to document storage

- gws-core/src/main/java/au/gov/ga/geodesy/port/adapter/rest/SkeletonEndpoint.java
- gws-core/src/test/java/au/gov/ga/geodesy/port/adapter/rest/SkeletonEndpointITest.java
I think the better way to do this would be to add parsing of signal types into the support-rinex header class. That would definitely take me longer than this took me and we would still have the mapping of signal types to receiver type in the skeleton class.
Any thoughts on a better way to insert the signals into the header string? Maybe `len(headerString) - 80` (or 81 or whatever) would be nicer to get the lines in before the "END OF HEADER" line. Or splitting the string on \n and inserting in the second last element (which I looked into but it involved a lot more code than I expected).
> Add signal types to skeleton files
